exclude: .*migrations\/.*
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
  - repo: https://github.com/Riverside-Healthcare/djlint
    rev: v1.31.1
    hooks:
    - id: djlint
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/pycqa/isort 
    rev: 5.12.0 
    hooks: 
      - id: isort 
        name: isort (python)
  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.4
    hooks:
    - id: pylint
